const mongoose=require("mongoose");

const UserSchema=new mongoose.Schema({
    username:{
        type:String,
        require:true,
        min:3,
        max:20,
        unique:true
    },
    mobile:{
        type:String,
        require:true,
        unique:true,
        min:10
    },
    email:{
        type:String,
        require:true,
        max:50,
        unique:true
    },
    coverPic:{
        type:String,
        default:""
    },
    profilePic:{
        type:String,
        default:""
    },
    password:{
        type:String,
        require:true,
        min:6
    },
    followers:{
        type:Array,
        default:[]
    },
    followings:{
        type:Array,
        default:[]
    },
    isAdmin:{
        type:Boolean,
        default:false
    },
    desc:{
        type:String,
        default:"",
        max:50
    },
},
{timestamps:true},
);
module.exports=mongoose.model("User",UserSchema)